# Generated by Django 4.0.2 on 2022-03-15 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=20)),
                ('uen', models.PositiveIntegerField()),
                ('gst_registration', models.CharField(max_length=20)),
                ('sub_domain_url', models.CharField(max_length=50)),
                ('fiscal_year', models.DateField()),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
